image: gitpod/workspace-node

tasks:
  - name: Dev server
    init: npm install
    command: npm run dev

ports:
  - port: 5173
    onOpen: open-preview
    visibility: public

vscode:
  extensions:
    - dbaeumer.vscode-eslint
